name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            platform: linux
            arch: amd64
            ext: ""
          - os: ubuntu-latest
            target: windows
            platform: windows
            arch: amd64
            ext: ".exe"
          - os: macos-14
            target: macos-x86_64
            platform: darwin
            arch: amd64
            ext: ""
          - os: macos-14
            target: macos-arm64
            platform: darwin
            arch: arm64
            ext: ""

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          echo "COMMIT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      # Dependencies for Linux and Windows builds
      - name: Install Linux/Windows dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-mingw-w64 zip libgl1-mesa-dev xorg-dev

      # Dependencies for macOS
      - name: Install Raylib on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install raylib

      # Clone raylib for Linux and Windows targets
      - name: Clone raylib
        if: matrix.target == 'linux' || matrix.target == 'windows'
        run: git clone --depth=1 https://github.com/raysan5/raylib.git

      # Build using the Makefile
      - name: Build ${{ matrix.target }}
        run: make ${{ matrix.target }}

      # Rename the binary for packaging
      - name: Rename binary
        run: |
          mv gmenu-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }} gmenu-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Zip binary
        run: |
          zip gmenu-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}.zip gmenu-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: gmenu-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
